name: Publish RC

on:
  push:
    branches:
      - dev

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "$GITHUB_REF"
          echo "${{ github.actor }}"

  publish:
    name: Publish RC version
    if: ${{ github.actor != 'github-merge-queue[bot]' }}
    uses: ./.github/workflows/publish-common.yml
    with:
      with-update-package-lock: true
      commit-message: "chore: update package-locks"
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
