name: Publish Canary

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - dev

jobs:
  test:
    name: Save state
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo "module.exports = { HAS_ASSETS:true }" > ${{ github.workspace }}/scope.js
          echo "FILE_NAME=scope-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.FILE_NAME}}
          path: ${{ github.workspace }}/${{ env.FILE_NAME}}.js

      - name: Computed scope state
        id: scope
        uses: actions/github-script@v6
        with:
          script: |
            const processingScope = require('${{ github.workspace }}/${{ env.FILE_NAME}}.js');

            console.log(processingScope); 
            console.log(processingScope.HAS_ASSETS); 

  authorize:
    name: Authorize external pull request
    uses: ./.github/workflows/auth.yml

  publish:
    name: Canary version
    needs: [ authorize ]
    uses: ./.github/workflows/publish-common.yml
    with:
      ref: refs/pull/${{github.event.pull_request.number}}/merge
      auto-options: '--no-changelog'
      upload_assets: true
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
