name: Publish Canary

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - dev

jobs:
  authorize:
    name: Authorize external pull request
    uses: ./.github/workflows/auth.yml

  publish:
    name: Canary version
    needs: [ authorize ]
    uses: ./.github/workflows/publish-common.yml
    with:
      ref: refs/pull/${{github.event.pull_request.number}}/merge
      cmd: 'npm run release:rc'
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}

  release-notes:
    name: Build Changelog
    needs:
      - publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install
        run: |
          npm ci --no-audit
          echo "FROM_TAG=$(git merge-base --fork-point origin/main)" >> $GITHUB_ENV

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          fromTag: ${{ env.FROM_TAG }}
        env:
          GITHUB_TOKEN: ${{  secrets.GH_TOKEN }}

      - name: Changelog
        run: echo "${{ steps.github_release.outputs.changelog }}"
