name: Publish Canary

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - dev

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{github.event.pull_request.number}}/merge
          show-progress: false

      - name: Create "scope.json"
        run: |
          jq -n "{ HAS_ASSETS:true }" > ${{ github.workspace }}/scope.json

      - name: Upload "scope.json"
        uses: actions/upload-artifact@master
        with:
          name: scope-json
          path: ${{ github.workspace }}/scope.json

      - name: LIST
        run: |
          rm ${{ github.workspace }}/scope.json
          ls -R

      - name: Download "scope.json"
        id: download-scope
        uses: actions/download-artifact@master
        with:
          name: scope-json
          path: ${{ github.workspace }}/scope.json

      - name: LIST
        run: |
          ls -R    

      - name: Computed scope state
        id: scope
        uses: actions/github-script@v6
        with:
          script: |
            const d = await import('${{ github.workspace }}/scope.json')
            const processingScope = require('./scope.json');

            console.log(JSON.parse(processingScope));    
            console.log(JSON.parse(d));    

  authorize:
    name: Authorize external pull request
    uses: ./.github/workflows/auth.yml

  publish:
    name: Canary version
    needs: [ authorize ]
    uses: ./.github/workflows/publish-common.yml
    with:
      ref: refs/pull/${{github.event.pull_request.number}}/merge
      auto-options: '--no-changelog'
      upload_assets: true
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
