name: POC reuse workflow

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      STATE:
        description: "scope collection"
        value: ${{ jobs.poc-reuse.outputs.STATE }}

jobs:
  poc-reuse:
    runs-on: ubuntu-latest
    env:
      IS_PR: ${{ fromJSON(github.event_name == 'pull_request') }}
    outputs:
      STATE: ${{ steps.output.outputs.STATE }}
    steps:
      - uses: actions/checkout@v4

      - name: Context
        if: ${{ env.IS_PR }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${{ env.GITHUB_CONTEXT }}"

      - name: Write state
        id: state
        uses: actions/github-script@v7
        with:
          script: |
            const processing = require("./.github/processing-data.js");
            
            return processing();

      - name: Set "GITHUB_OUTPUT"
        id: output
        run: |
          echo "STATE=${{ steps.state.outputs.result }}" >> $GITHUB_OUTPUT
