name: Status

on:
  - status

jobs:
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: github.event.state == 'success'
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo "${{ github.event }}"
          echo The status is error or failed: $DESCRIPTION
